# Generated by Django 5.0.2 on 2024-05-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_singleaudiofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_audio', models.CharField(max_length=255)),
                ('compared_audio', models.CharField(max_length=255)),
                ('similarity', models.BooleanField()),
            ],
        ),
    ]
